//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demeter_v2.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Survival
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your land intensity.")]
        public string Intensity { get; set; }
        [Required(ErrorMessage = "Please enter your land seeding.")]
        public string Seeding { get; set; }
        [Required(ErrorMessage = "Please enter your land area size.")]
        public string Area { get; set; }
        public string SurvivalResult { get; set; }


    }
}
