//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demeter_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survival
    {
        public int Id { get; set; }
        public string Intensity { get; set; }
        public string Seeding { get; set; }
        public string Area { get; set; }
        public string SurvivalResult { get; set; }
    }
}
